# Generated by Django 3.2 on 2022-12-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='nc_value',
            field=models.IntegerField(verbose_name='Valor NC'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='observations',
            field=models.TextField(verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='quantity_tickets',
            field=models.IntegerField(verbose_name='Cantidad Tickets'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='quantity_units',
            field=models.IntegerField(verbose_name='Cantidad Unidades'),
        ),
    ]
