# Generated by Django 3.2 on 2022-12-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20221206_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='locked',
            field=models.BooleanField(default=False, verbose_name='Bloqueado?'),
        ),
    ]
