# Generated by Django 3.2 on 2022-12-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sales_locked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='locked',
        ),
        migrations.AddField(
            model_name='sales',
            name='can_edit',
            field=models.BooleanField(default=True, verbose_name='Bloqueado?'),
        ),
    ]
