# Generated by Django 3.2 on 2022-12-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20221206_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='can_edit',
            field=models.BooleanField(default=True, verbose_name='¿Puede Editar?'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='nc_value',
            field=models.FloatField(verbose_name='Valor NC'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='quantity_tickets',
            field=models.FloatField(verbose_name='Cantidad Tickets'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='quantity_units',
            field=models.FloatField(verbose_name='Cantidad Unidades'),
        ),
    ]
